---
name: "公众号写作助手"
version: "9.0.0"
description: "基于82篇数据验证的三层架构爆款系统。配置驱动、优先级公式、Layer1/2/3选题过滤"

# 核心配置
config:
  data_source: "config/*.json"
  architecture: "三层架构"
  priority_formula: "layer_score × timeliness × type_weight × brand_tier ÷ risk"

# 触发关键词
triggers:
  keywords:
    - "/write"
    - "/write-auto"
    - "/write-rewrite"
    - "/scan"
    - "/daily"
    - "/title-gen"
    - "/title-score"
    - "/pre-check"
    - "/topic-filter"
    - "/image"
    - "/infographic"
    - "/collect"
    - "/analyze"
    - "/help"
    - "公众号"
    - "写文章"
    - "老金风格"
    - "热点扫描"
    - "爆款"
    - "标题"

# 命令系统
commands:
  help:
    code: "02-help"
    description: "帮助中心"

  write:
    code: "03-write"
    description: "完整写作流程"

  write_auto:
    code: "04-write-auto"
    description: "全自动爆款生成"

  write_rewrite:
    code: "05-write-rewrite"
    description: "文章翻新改写"

  title_gen:
    code: "21-title-gen"
    description: "生成爆款标题"
    script: "scripts/core/title_generator.py"

  title_score:
    code: "22-title-score"
    description: "标题评分"
    script: "scripts/core/title_scorer.py"

  pre_check:
    code: "23-pre-check"
    description: "发文前检查"
    script: "scripts/core/pre_publish_checker.py"

  topic_filter:
    code: "24-topic-filter"
    description: "三层架构选题过滤"
    script: "scripts/core/topic_filter.py"

  scan:
    code: "51-scan"
    description: "三层架构热点扫描"

  daily:
    code: "52-daily"
    description: "每日热点+自动写作"

  image:
    code: "31-image"
    description: "自动添加配图"

  infographic:
    code: "32-infographic"
    description: "生成信息图"
    script: "scripts/infographic_generator.py"

  collect:
    code: "41-collect"
    description: "收集微信公众号数据"

  analyze:
    code: "42-analyze"
    description: "深度分析文章数据"

# 核心脚本
scripts:
  core:
    - "scripts/core/title_generator.py"
    - "scripts/core/title_scorer.py"
    - "scripts/core/pre_publish_checker.py"
    - "scripts/core/topic_filter.py"
    - "scripts/core/ecosystem_filter.py"
    - "scripts/core/quality_detector.py"
  utils:
    - "scripts/infographic_generator.py"
    - "scripts/analyze_wechat_data.py"

# 配置文件
config_files:
  - "config/core_tools_pool.json"
  - "config/brands_config.json"
  - "config/formulas_config.json"
  - "config/quality_config.json"

# 质量标准
quality_standards:
  ai_score: "< 20"
  natural_score: "> 80"
  sincere_score: "> 75"
  title_min_score: 60

# 三层架构数据基准
layer_benchmarks:
  layer1:
    name: "核心工具官方"
    avg_reads: 2200
    boom_rate: "71%"
  layer2:
    name: "核心工具生态"
    avg_reads: 1450
    boom_rate: "24%"
  layer3:
    name: "泛AI话题"
    avg_reads: 908
    boom_rate: "5%"
